// Code generated by protoc-gen-go.
// source: Record.proto
// DO NOT EDIT!

/*
Package Record is a generated protocol buffer package.

It is generated from these files:
	Record.proto

It has these top-level messages:
	Record
*/
package Record

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Record struct {
	Userid           *int32  `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Timestamp        *int32  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Cmd              *string `protobuf:"bytes,3,opt,name=cmd" json:"cmd,omitempty"`
	Ip               *uint32 `protobuf:"varint,4,opt,name=ip" json:"ip,omitempty"`
	Version          *int32  `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	Platform         *string `protobuf:"bytes,6,opt,name=platform" json:"platform,omitempty"`
	Devicesign       *string `protobuf:"bytes,7,opt,name=devicesign" json:"devicesign,omitempty"`
	Provider         *string `protobuf:"bytes,8,opt,name=provider" json:"provider,omitempty"`
	Account          *string `protobuf:"bytes,9,opt,name=account" json:"account,omitempty"`
	Action           *string `protobuf:"bytes,10,opt,name=action" json:"action,omitempty"`
	Metatag          *string `protobuf:"bytes,11,opt,name=metatag" json:"metatag,omitempty"`
	Sid              *uint32 `protobuf:"varint,12,opt,name=sid" json:"sid,omitempty"`
	Cs               *uint32 `protobuf:"varint,13,opt,name=cs" json:"cs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}

func (m *Record) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *Record) GetTimestamp() int32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Record) GetCmd() string {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ""
}

func (m *Record) GetIp() uint32 {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return 0
}

func (m *Record) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Record) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

func (m *Record) GetDevicesign() string {
	if m != nil && m.Devicesign != nil {
		return *m.Devicesign
	}
	return ""
}

func (m *Record) GetProvider() string {
	if m != nil && m.Provider != nil {
		return *m.Provider
	}
	return ""
}

func (m *Record) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *Record) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *Record) GetMetatag() string {
	if m != nil && m.Metatag != nil {
		return *m.Metatag
	}
	return ""
}

func (m *Record) GetSid() uint32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *Record) GetCs() uint32 {
	if m != nil && m.Cs != nil {
		return *m.Cs
	}
	return 0
}

func init() {
}
